default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] %>
